//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHDNHAP
    {
        public int MANL { get; set; }
        public int MAHDNHAP { get; set; }
        public Nullable<int> SOLUONGHANGNHAP { get; set; }
        public Nullable<double> THANHTIENCTHDNHAP { get; set; }
        public Nullable<double> CONGNO { get; set; }
    
        public virtual HOADONNHAP HOADONNHAP { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
