//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENLIEU
    {
        public NGUYENLIEU()
        {
            this.CHITIETHDNHAPs = new HashSet<CHITIETHDNHAP>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MaNL { get; set; }
        public string TenNL { get; set; }
        public Nullable<int> SoLuongCon { get; set; }
        public string DVT { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<System.DateTime> HanSD { get; set; }
    
        public virtual ICollection<CHITIETHDNHAP> CHITIETHDNHAPs { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
