//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.HOADONNHAPs = new HashSet<HOADONNHAP>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public int MANV { get; set; }
        public string TENNV { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string SDT { get; set; }
        public string CHUCVU { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<HOADONNHAP> HOADONNHAPs { get; set; }
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
