//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
            this.NGUYENLIEUx = new HashSet<NGUYENLIEU>();
        }
    
        public int MASP { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public string TENSP { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public string HINHANH { get; set; }
    
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual ICollection<NGUYENLIEU> NGUYENLIEUx { get; set; }
    }
}
